Event.seed ->
    longitude: "-122.4413014"
    organizer: "Joey Bishop"
    time: "3pm"
    date: "Thursday June 23rd"
    latitude: "37.7755105"
    title: "Writing tests can be fun"
    address: "94117 Grove Street, San Francisco, CA"
    description: "Tests can be fun if you know what your doing. Learn how here."
Event.seed ->
    longitude: "-122.4413014"
    organizer: "Joey Bishop"
    time: "3pm"
    date: "Thursday June 23rd"
    latitude: "37.7755105"
    title: "Writing tests can be fun"
    address: "94117 Grove Street, San Francisco, CA"
    description: "Tests can be fun if you know what your doing. Learn how here."
Event.seed ->
    longitude: "-122.4413014"
    organizer: "Joey Bishop"
    time: "3pm"
    date: "Thursday June 23rd"
    latitude: "37.7755105"
    title: "Writing tests can be fun"
    address: "94117 Grove Street, San Francisco, CA"
    description: "Tests can be fun if you know what your doing. Learn how here."
Event.seed ->
    longitude: "-122.4413014"
    organizer: "Joey Bishop"
    time: "3pm"
    date: "Thursday June 23rd"
    latitude: "37.7755105"
    title: "Writing tests can be fun"
    address: "94117 Grove Street, San Francisco, CA"
    description: "Tests can be fun if you know what your doing. Learn how here."
Event.seed ->
    longitude: "-122.437515"
    organizer: "Amoe.ba"
    date: "Thursday July 23, 2014"
    latitude: "37.750842"
    title: "Coding with Ruby"
    address: "4255 24th Street, San Francisco, CA"
    description: "Learn to code Ruby with the guys from Amoeba."
Event.seed ->
    longitude: "-122.4272268"
    organizer: "Sara Williams"
    date: "Friday, January 2nd, 2pm"
    latitude: "37.7635132"
    title: "Code by the Park"
    address: "94114 Abbey Street, San Francisco, CA"
    description: "Sit around Dolores Park and write code"
Event.seed ->
    longitude: "-122.4216058"
    organizer: "Dr. Dirk Dirkland"
    date: "Friday June 23rd, 3pm - 8pm"
    latitude: "37.7784056"
    title: "Cobol for the Web"
    address: "94102 Franklin Street, San Francisco, CA"
    description: "Don't want to learn those new fancy smancy languages like Javascript? Use Cobol!"
Event.seed ->
    longitude: "-122.4092099"
    organizer: "Amoe.ba"
    date: "Wed March 23, 2014"
    latitude: "37.7608724"
    title: "Coding with Python"
    address: "660 York Street, San Francisco, CA"
    description: "Learn to code Python with the guys from Amoeba."
